name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-to-cloudflare:
    uses: ubiquity/.github/.github/workflows/deploy.yml@ci/deploy-v2
    secrets: inherit
